name: Broken Link Check
on:
  schedule:
    - cron: '0 0 * * *' # Run daily
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html'